### PR TITLE
Created Scheduler.py

### PR DESCRIPTION
**Pull request by Cheemashyper**
Solved Issue  #272 
Added a Simple Schedule Event Program as Requested.

### CODE REVIEW

**Comment by Cheemashyper** [comment]
Hello @avsingh999 ,
Added the Schedule Event Code as requested.

**Comment by avsingh999** [comment]
Please add .md file for this and update also in Readme.md  about this file

**Comment by Cheemashyper** [comment]
I am sorry @avsingh999 ,
But i don't know how to make .md Files
Can you make it for me?

**Comment by avsingh999** [comment]
@Cheemashyper  I have added the Scheduler.md file 

Thansk :smile:

**Pull request merged**
