### PR TITLE
Fix #77 - simple gui in tinker python

### LINKED ISSUE #77: simple gui in tkinter python?
#### create .md file name should be a title of the issue
:heart:
Thank you

### PR DESCRIPTION
**Pull request by a96tudor**
Hi, 

Here is my simple tkinter app. 
Looking forward for your feedback.

Thanks, 
Tudor.

### CODE REVIEW

**Comment by avsingh999** [comment]
@a96tudor  please add a screenshot of this gui
thanks :)

**Comment by avsingh999** [comment]
@a96tudor  please add only .md file 
thanks

**Comment by ulshell** [comment]
Hello I have done in .md

**Comment by avsingh999** [comment]
@ulshell great job
thanks :)

**Pull request merged**
